# Generated by Django 5.2.6 on 2025-09-05 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email",
            name="is_read",
        ),
        migrations.RemoveField(
            model_name="email",
            name="is_sent",
        ),
        migrations.RemoveField(
            model_name="email",
            name="recipients",
        ),
        migrations.AddField(
            model_name="email",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_emails",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_emails",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
